import type { PlugParkPlace } from './types';

export const mockPlaces: PlugParkPlace[] = [
  {
    id: 'mock-centum',
    name: '센텀시티 공영주차장',
    address: '부산광역시 해운대구 센텀 일대',
    agency: '부산광역시 해운대구',
    lat: 35.1699,
    lng: 129.1302,
    capacity: 120,
    availableParking: 37,
    occupiedParking: 83,
    feeText: '10분 300원 · 예시 데이터',
    operationText: '24시간 · 예시 데이터',
    parkingUpdatedAt: null,
    parkingRealtime: false,
    parkingSource: 'busan-city',
    charger: {
      total: 4,
      available: 3,
      availableFast: 2,
      availableSlow: 1,
      charging: 1,
      fast: 2,
      slow: 2,
      stations: ['센텀 EV 충전소'],
      nearestDistanceMeters: 42,
      lastUpdated: null,
      matchConfidence: null,
    },
    source: 'mock',
  },
  {
    id: 'mock-station',
    name: '부산역 공영주차장',
    address: '부산광역시 동구 부산역 일대',
    agency: '부산광역시 동구',
    lat: 35.1152,
    lng: 129.0422,
    capacity: 60,
    availableParking: 14,
    occupiedParking: 46,
    feeText: '10분 300원 · 예시 데이터',
    operationText: '운영시간 확인 필요',
    parkingUpdatedAt: null,
    parkingRealtime: false,
    parkingSource: 'busan-city',
    charger: {
      total: 2,
      available: 1,
      availableFast: 1,
      availableSlow: 0,
      charging: 1,
      fast: 1,
      slow: 1,
      stations: ['부산역 EV 충전소'],
      nearestDistanceMeters: 76,
      lastUpdated: null,
      matchConfidence: null,
    },
    source: 'mock',
  },
  {
    id: 'mock-gwangalli',
    name: '광안리 공영주차장',
    address: '부산광역시 수영구 광안리 일대',
    agency: '부산광역시 수영구',
    lat: 35.1532,
    lng: 129.1187,
    capacity: 55,
    availableParking: 8,
    occupiedParking: 47,
    feeText: '현장 요금 확인 · 예시 데이터',
    operationText: '운영시간 확인 필요',
    parkingUpdatedAt: null,
    parkingRealtime: false,
    parkingSource: 'busan-city',
    charger: {
      total: 3,
      available: 2,
      availableFast: 1,
      availableSlow: 1,
      charging: 1,
      fast: 2,
      slow: 1,
      stations: ['광안리 EV 충전소'],
      nearestDistanceMeters: 108,
      lastUpdated: null,
      matchConfidence: null,
    },
    source: 'mock',
  },
];
